package recipeBot;

public enum State {
    WAITING_FOR_NAME,
    WAITING_FOR_CATEGORY,
    WAITING_FOR_INGREDIENTS,
    WAITING_FOR_INSTRUCTIONS,
    WAITING_FOR_DESCRIPTION,
    WAITING_FOR_URL,
    WAITING_FOR_IMAGE,
    EDITING_NAME,
    EDITING_CATEGORY,
    EDITING_INGREDIENTS,
    EDITING_INSTRUCTIONS,
    EDITING_DESCRIPTION,

}
