package recipeBot;

public enum State {
    WAITING_FOR_NAME,
    WAITING_FOR_CATEGORY,
    WAITING_FOR_INGREDIENTS,
    WAITING_FOR_INSTRUCTIONS,
    WAITING_FOR_DESCRIPTION,
    WAITING_FOR_URL,
    WAITING_FOR_VISIBILITY,
    WAITING_FOR_NEW_CATEGORY,
    EDITING_NAME,
    EDITING_INGREDIENTS,
    EDITING_INSTRUCTIONS,
    EDITING_DESCRIPTION,
    EDITING_CALORIES,
    RENAMING_CATEGORY,
}
